<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.03" />

    <joint name="base_front_camera_joint" type="fixed">
        <parent link="base_front_link" />
        <child link="camera_link" />
        <origin xyz="${(boundary_thickness + camera_length) / 2.0} 0 ${(base_height + 2.0 * boundary_thickness) * 2.0 / 6.0}" rpy="0 0 0" />
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="dark_gray" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertial mass="0.1" size="${camera_length} ${camera_width} ${camera_height}" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
    </link>

    <gazebo>
        <plugin name="gz::sim::systems::Sensors" filename="gz-sim-sensors-system" >
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <camera_info_topic>camera/camera_info</camera_info_topic>
                <optical_fram_id>camera_link</optical_fram_id>
            </camera>
            <frame_id>camera_link</frame_id>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>
        </sensor>
    </gazebo>

</robot>