<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.025"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.05" radius="0.025"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="0.03" length="0.05" radius="0.025" origin_xyz="0 0 0" origin_rpy="0 0 0" />
    </link>

    <joint name="top_lidar_joint" type="fixed">
        <parent link="base_top_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${(boundary_thickness + 0.05) / 2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
        <sensor type="gpu_lidar" name="gpu_lidar">
        <!-- <sensor type="ray" name="lidar"> -->
            <pose relative_to="lidar_link">0 0 0 0 0 0</pose>
            <always_on>1</always_on>
            <visualize>true</visualize>
            <update_rate>30</update_rate>
            <topic>lidar/pointcloud</topic>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>32</samples>
                        <resolution>1</resolution>
                        <min_angle>-0.5</min_angle>
                        <max_angle>0.5</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>0.8</min>
                    <max>20.0</max>
                    <resolution>0.001</resolution>
                </range>  
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </lidar>
        </sensor>
    </gazebo>

</robot>
