<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>

    <xacro:property name="wheel_radius" value="${base_height / 2.0}"/>
    <xacro:property name="wheel_length" value="${wheel_radius / 2.0}"/>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="red"/>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </visual>
             <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertial mass="1.0" radius="${wheel_radius}" length="${wheel_length}" origin_xyz="0 0 0" origin_rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${(base_height + wheel_radius) / 2.0}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="green"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertial mass="5.0" size="${base_length} ${base_width} ${base_height}" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
    </link>

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="${- base_length / 4.0} ${+ (base_width + wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="rear_left" />

    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="${- base_length / 4.0} ${- (base_width + wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="rear_right" />

     <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${+ base_length / 4.0} ${+ (base_width + wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_left" />

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${+ base_length / 4.0} ${- (base_width + wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="front_right" />
</robot>