<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo reference="rear_left_caster_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="rear_right_caster_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="front_left_caster_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo reference="front_right_caster_wheel">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <left_joint>base_left_wheel_joint</left_joint>
            <right_joint>base_right_wheel_joint</right_joint>
            <wheel_separation>${base_width - (wheel_length + epsilon)}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>50</odom_publish_frequency>
            <frame_id>odom</frame_id>
            <child_frame_id>base_footprint</child_frame_id>
            <topic>/cmd_vel</topic>
            <odom_topic>/odometry</odom_topic>
            <tf_topic>/tf</tf_topic>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <!-- <joint_name>base_left_wheel_joint</joint_name>
            <joint_name>base_right_wheel_joint</joint_name> -->
            <topic>/joint_states</topic>
        </plugin>
    </gazebo>

</robot>