<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>

    <xacro:property name="wheel_radius" value="${base_height / 2.0}"/>
    <xacro:property name="wheel_length" value="${wheel_radius / 2.0}"/>

    <xacro:property name="caster_wheel_radius" value="${wheel_radius / 2.0}" />

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="red" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertial mass="0.5" radius="${wheel_radius}" length="${wheel_length}" origin_xyz="0 0 0" origin_rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:macro name="caster_wheel" params="prefix">
        <link name="${prefix}_caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}" />
                </geometry>
                <material name="gray" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial mass="0.25" radius="${caster_wheel_radius}" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_height / 2.0 + wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="green"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertial mass="5.0" size="${base_length} ${base_width} ${base_height}" origin_xyz="0 0 0" origin_rpy="0 0 0"/>
    </link>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 ${+ (base_width - wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="left" />

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 ${- (base_width - wheel_length) / 2.0} ${- base_height / 2.0}" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <xacro:wheel_link prefix="right" />

    <joint name="base_rear_left_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_left_caster_wheel" />
        <origin xyz="${- base_length / 3.0} ${+ (base_width / 2.0 - caster_wheel_radius)} ${- (base_height / 2.0 + caster_wheel_radius)}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel prefix="rear_left"/>

    <joint name="base_rear_right_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_right_caster_wheel" />
        <origin xyz="${- base_length / 3.0} ${- (base_width / 2.0 - caster_wheel_radius)} ${- (base_height / 2.0 + caster_wheel_radius)}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel prefix="rear_right"/>

    <joint name="base_front_left_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_left_caster_wheel" />
        <origin xyz="${+ base_length / 3.0} ${+ (base_width / 2.0 - caster_wheel_radius)} ${- (base_height / 2.0 + caster_wheel_radius)}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel prefix="front_left"/>

    <joint name="base_front_right_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_right_caster_wheel" />
        <origin xyz="${+ base_length / 3.0} ${- (base_width / 2.0 - caster_wheel_radius)} ${- (base_height / 2.0 + caster_wheel_radius)}" rpy="0 0 0" />
    </joint>

    <xacro:caster_wheel prefix="front_right"/>

</robot>