- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/joint_states"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/tf"
#   gz_topic_name: "/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/odometry"
#   gz_topic_name: "/odometry"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/depth_camera"
  gz_topic_name: "/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/depth_camera/points"
  gz_topic_name: "/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/imu/data_raw"
  gz_topic_name: "/imu/data_raw"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/lidar/pointcloud"
  gz_topic_name: "/lidar/pointcloud"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  lazy: false

- ros_topic_name: "/lidar/pointcloud/points"
  gz_topic_name: "/lidar/pointcloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: false

# - ros_topic_name: "/cmd_vel"
#   gz_topic_name: "/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ

- ros_topic_name: "/battery/state"
  gz_topic_name: "/model/mobile_robot/battery/linear_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "gz.msgs.BatteryState"
  direction: GZ_TO_ROS

- ros_topic_name: "/battery/recharge/start"
  gz_topic_name: "/model/mobile_robot/battery/linear_battery/recharge/start"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ

- ros_topic_name: "/battery/recharge/stop"
  gz_topic_name: "/model/mobile_robot/battery/linear_battery/recharge/stop"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ

- ros_service_name: "/battery/recharge/start"
  gz_service_name: "/model/mobile_robot/battery/linear_battery/recharge/start"
  ros_request_type: "std_srvs/srv/SetBool"
  gz_request_type: "gz.msgs.Boolean"
  ros_response_type: "std_srvs/srv/Empty"
  gz_response_type: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_service_name: "/battery/recharge/stop"
  gz_service_name: "/model/mobile_robot/battery/linear_battery/recharge/stop"
  ros_request_type: "std_srvs/srv/SetBool"
  gz_request_type: "gz.msgs.Boolean"
  ros_response_type: "std_srvs/srv/Empty"
  gz_response_type: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/battery/discharge/start"
  gz_topic_name: "/battery/discharge/start"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ

- ros_topic_name: "/battery/discharge/stop"
  gz_topic_name: "/battery/discharge/stop"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "gz.msgs.Empty"
  direction: ROS_TO_GZ


